# Generated by Django 2.1.2 on 2018-10-07 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeCareApp', '0002_auto_20181007_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='name',
        ),
    ]
